import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "NVFA Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`bg-white-50 antialiased overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
